version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-automation
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
      - ./processed:/app/processed
      - ./temp:/app/temp
      - ./credentials:/app/credentials
      - ./backups:/app/backups
      - ./shorts:/app/shorts
      - ./thumbnails:/app/thumbnails
    networks:
      - youtube-automation
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: youtube-automation-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - youtube-automation
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  youtube-automation:
    driver: bridge
